name: Build all platforms

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  # buildWin64:
  #   name: Build for Win64 ✨
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         lfs: true

  #     # Cache
  #     - uses: actions/cache@v3
  #       with:
  #         path: Library
  #         key: Library-${{ hashFiles('ReactionGame/Assets/**', 'ReactionGame/Packages/**', 'ReactionGame/ProjectSettings/**') }}
  #         restore-keys: |
  #           Library-

  #     # Build
  #     - name: Build project
  #       uses: game-ci/unity-builder@v2
  #       env:
  #         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #       with:
  #         targetPlatform: StandaloneWindows64
  #         projectPath: ReactionGame/
  #         buildsPath: ReactionGame/Build

  #     # Output
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: CatchWin64
  #         path: |
  #           ReactionGame/Build/StandaloneWindows64/
  #           !ReactionGame/Build/StandaloneWindows64/*DoNotShip/
       
  KAndroid build
  buildAndroid:
    name: Build for Android 📱
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('ReactionGame/Assets/**', 'ReactionGame/Packages/**', 'ReactionGame/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          projectPath: ReactionGame/
          buildsPath: ReactionGame/Build
          androidTargetSdkVersion: 31

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: CatchDroid
          path: |
            ReactionGame/Build/Android/
            !ReactionGame/Build/Android/*DoNotShip/

  # buildWeb:
  #   name: Build for Web ✨
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         lfs: true

  #     # Cache
  #     - uses: actions/cache@v3
  #       with:
  #         path: Library
  #         key: Library-${{ hashFiles('ReactionGame/Assets/**', 'ReactionGame/Packages/**', 'ReactionGame/ProjectSettings/**') }}
  #         restore-keys: |
  #           Library-

  #     # Build
  #     - name: Build project
  #       uses: game-ci/unity-builder@v2
  #       env:
  #         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #         UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #         UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #       with:
  #         targetPlatform: WebGL
  #         projectPath: ReactionGame/
  #         buildsPath: ReactionGame/Build

  #     # Output
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: CatchWeb
  #         path: |
  #           ReactionGame/Build/WebGL/
  #           !ReactionGame/Build/WebGL/*DoNotShip/
